version: "3.8"

services:
  master:
    image: bitnami/redis
    volumes:
      - ./modules:/bitnami/redis/modules
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${MASTER_PASSWORD}
    ports:
      - '6379:6379'

  slave:
    image: bitnami/redis
    volumes:
      - ./data:/bitnami/redis/data
      - ./modules:/bitnami/redis/modules
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_PASSWORD=${MASTER_PASSWORD}
    depends_on:
      - master
    ports:
      - '6380:6379'

  injector:
    image: redis:latest
    depends_on:
      - master
      - slave
    links:
      - master
      - slave
    entrypoint: 
      bash -c "redis-cli -a ${MASTER_PASSWORD} -h master -p 6379 MODULE LOAD /bitnami/redis/modules/rejson.so && redis-cli -a ${MASTER_PASSWORD} -h slave -p 6379 MODULE LOAD /bitnami/redis/modules/rejson.so"
    environment:
      - REDIS_MASTER_HOST=master

  sentinel:
    image: bitnami/redis-sentinel
    environment:
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=6000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=6000
    depends_on:
      - master
      - slave
    ports: 
      - '26379-26381:26379'
    
networks:
  default:
    name: redis_cluster
