version: "3.8"

services:
  master:
    image: bitnami/redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_PASSWORD=${MASTER_PASSWORD}
    ports:
      - '6379:6379'

  slave:
    image: bitnami/redis
    volumes:
      - ./data:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_PASSWORD=${REPLICA_PASSWORD}
    depends_on:
      - master
    ports:
      - '6380:6379'

  sentinel:
    image: bitnami/redis-sentinel
    environment:
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=6000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=6000
    depends_on:
      - master
      - slave
    ports: 
      - '26379-26381:26379'
    
networks:
  default:
    name: redis_cluster
