version: "3.8"

services:
  master:
    image: bitnami/redis
    environment:
      - REDIS_REPLICATION_NODE=master
      - REDIS_PASSWORD=${MASTER_PASSWORD}
    ports:
      - '6379'

  slave:
    image: bitnami/redis
    volumes:
      - ./data:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${MASTER_PASSWORD}
      - REDIS_PASSWORD=${REPLICA_PASSWORD}
    depends_on:
      - master
    ports:
      - '6379'

  sentinel:
    image: bitnami/redis-sentinel
    environment:
      - REDIS_MASTER_HOST=master
    volumes:
      - ./conf/sentinel.conf:/bitnami/sentinel/conf/sentinel.conf
    depends_on:
      - master
    ports: 
      - '5000'
    
networks:
  default:
    name: redis_cluster
